project_robot_888888:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  # Position Controllers ---------------------------------------
  left_wheel_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_up_left_joint
    pid: {p: 5.0, i: 20, d: 0.0, i_clamp: 100.0}
  right_wheel_controller:
    type: effort_controllers/JointVelocityController
    joint: wheel_up_right_joint
    pid: {p: 5.0, i: 20, d: 0.0, i_clamp: 100.0}